spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dsa_lab}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # No table creation for now refer resources/dsa_lab_schema.sql
    show-sql: true
    properties:
      hibernate:
        default-schema: dsa_lab
    open-in-view: false

server:
  port: 8080

jwt:
  secret: "ThisIsASecureKeyThatIsAtLeast256BitsLong"  # Plain text secret
  expiration-ms: 3600000
